### PR TITLE
Import EventEmitter differently depending on version

### LINKED ISSUE #228: class heritage EventEmitter is not an object or null
When I call `browser.study.setup`, I get the following error:
```
class heritage EventEmitter is not an object or null api.js:8222
Error: An unexpected error occurred main.js:3:27 
```

The exact same code worked a week ago, so it looks like a recent change in Firefox broke this.
@rhelmer investigated a bit and found that `EventEmitter` was moved from `ExtensionUtils` to `ExtensionCommon`.

```javascript
ChromeUtils.import("resource://gre/modules/ExtensionUtils.jsm");
const { EventEmitter, ExtensionError } = ExtensionUtils;
EventEmitter // => undefined
```

The same code with ExtensionCommon works as expected.
I tried to create a PR for this, but `npm run build` errors out on the current master version of this repo, so it's hard to test the change.

### PR DESCRIPTION
**Pull request by florian**
This PR fixes #228.
Currently the study library in this repo is broken in Nightly because [`EventEmitter` was moved from `ExtensionUtils` to `ExtensionCommon`](https://bugzilla.mozilla.org/show_bug.cgi?id=1471102).

This is a small change that checks if `EventEmitter` could be imported from `ExtensionCommon` and otherwise imports it from `ExtensionUtils`.
The build process does not work for me, so I'm not sure if this actually fixes everything. Maybe other imports have to be changed, too. But at least the `EventEmitter` import works properly for me in Nightly and Beta like this.

### CODE REVIEW

**Comment by motin** [comment]
Thanks, I changed the base of this PR to the `develop` branch in order to comply with current release and npm publishing routines. The code does not currently lint (can be fixed with `npm run format`)

**Comment by florian** [comment]
I've run `npm run format` and pushed the change. That command also changed a bunch of Markdown files, but I only committed the JS file that I changed earlier.

**Comment by motin** [comment]
Thanks, super! Merged this into the release candidate for 5.0.3, which is reviewed at https://github.com/mozilla/shield-studies-addon-utils/pull/220 before merge to master.

**Comment by florian** [comment]
Great, thanks!

**Pull request merged**
