### PR TITLE
Add normandy unenroll listener

### LINKED ISSUE #154: handle shield study permissions revoked.
This SHOULD be a standard ending, but we don't have one for it.

### PR DESCRIPTION
**Pull request by motin**
- [x] Make onEndStudy fire upon Normandy unenrollment
- [ ] Make sure that the Promise returned to Normandy resolves only when onEndStudy is finished executing

Automatic tests (which could be modeled after https://searchfox.org/mozilla-central/source/toolkit/components/normandy/test/unit/test_addon_unenroll.js) have been omitted since this is merely a stop-gap fix to support study add-ons until study utils are added to tree. 

Please review and advice on how we can test this manually. 

Fixes 1 out of 2 outstanding issues outlined in https://github.com/mozilla/shield-studies-addon-utils/issues/246
Fixes https://github.com/mozilla/shield-studies-addon-utils/issues/267
Fixes #154

### CODE REVIEW

**Comment by mythmon** [comment]
For manual testing, you'll need to actually enroll an add-on in a study that contains this code. The easiest way to currently do this would be to create a recipe on the Normandy Stage server, and point a Firefox profile to that server. I can help with this on Slack, if you don't already have what you need for that.

**Comment by motin** [comment]
@mythmon Great! Will ping on Skype regarding manual testing.

Another question: based on a quick source code inspection, the reason sent when the study gets unenrolled by Normandy is "shield-study-ended". A user clicking unenroll yields "individual-opt-out".

What reason is sent if Normandy pulls back a study? For studies that open up a survey, it is important to be able to skip opening up the survey in such a case.

**Comment by motin** [comment]
Possible answering my own question, I see that [the docs](https://firefox-source-docs.mozilla.org/toolkit/components/normandy/normandy/data-collection.html) mention the following reasons:

**Comment by mythmon** [comment]
"The study was pulled back" would be seen as `recipe-not-seen`, since the client does not see or execute disabled recipes. I'm not sure what you mean by `shield-study-ended`.

**Comment by motin** [comment]
Summary of our conversation on Slack: Currently `recipe-not-seen` is what the client sees upon natural study end and in case the study was pulled pack, thus we will not be opening any surveys upon `recipe-not-seen`.

**Pull request merged**
