### PR TITLE
Add prettier support, via 'npm run format'

### PR DESCRIPTION
**Pull request by pdehaan**
Dearest @gregglind,

You can see what I mean about it being a pretty sizable (and unstable) diff.
Prettier doesn't offer a _ton_ of configuration options, but if there is something you find horribly offensive below, I think we can do some "ignore" blocks for certain code, or add specific files/folders/extensions to the .prettierignore file.

### CODE REVIEW

**Comment by gregglind** [comment]
Main comment:  perhaps I am ignorant, but this feels like eslint, and prettier are in conflict about many aspects here.  

I appreciate the work on this, and trying to see how gory the changes are!  Some seem obviously good and some seem... gory!

/me off to look more at how prettier work.

**Comment by gregglind** [comment]
https://github.com/prettier/prettier-eslint/issues/101

**Comment by pdehaan** [comment]
Yeah, Prettier and ESLint rules and configs can definitely conflict, so it's generally better to disable any Prettier formatting-related rules (quotes, trailing commas, spacing) in ESLint so they don't fight each other.

Or if you want to go the "prettier in eslint" route, I can try submitting a separate PR for that so we can battle them side-by-side. I've gotten it working in the past, but sometimes formatting errors will show up in ESLint with less than helpful error messages.

**Comment by pdehaan** [comment]
But let me know if you have any specific "gore" that you want me to research. Naturally we can have Prettier ignore JSON files, or Markdown files or other things where formatting is less helpful.

**Comment by gregglind** [comment]
Mostly I need to learn a lot more about what things it has opinions on.
The only one that annoyed me was collapsing arrays :).

How can we play best with Mozilla code in general :)

**Comment by motin** [comment]
In the template, this is currently under review. 
By using a combination of prettier + eslint --fix the code does not go against any eslint rules. 
I am all for using this for addon-utils as well. It will not result in code formatted to everyone's liking, but that is the point and philosophy of prettier, to force one standard code style and avoid having to discuss what code style to agree on.
I will open a new PR for this based on the latest branches as soon as existing PRs have been merged or closed.

**Comment by motin** [comment]
The changes in this PR were rebased and included in #119 which is now merged.

**Pull request closed without merging**
